fix(cli): fix

diff --git a/jobdone-nexus-cli b/jobdone-nexus-cli
--- a/jobdone-nexus-cli
+++ b/jobdone-nexus-cli
@@ -56,9 +56,9 @@ log() {
     echo "$(date +%Y-%m-%dT%H:%M:%S) - $1" | tee -a $log_file
 }
 
-# install basic pacakges
-sudo apt update &>> $log_file || { log "Failed to update apt."; exit 1; }
-sudo apt install -y curl sudo vim htop git net-tools wget ncdu network-manager &>> $log_file || { log "Failed to install basic packages."; exit 1; }
+# install basic pacakges as root
+apt update &>> $log_file || { log "Failed to update apt."; exit 1; }
+apt install -y curl sudo vim htop git net-tools wget ncdu network-manager &>> $log_file || { log "Failed to install basic packages."; exit 1; }
 
 # k3s
 if ! k3s --version &> /dev/null; then
