fix(script): do not log stream to log file

diff --git a/jobdone-nexus-cli b/jobdone-nexus-cli
--- a/jobdone-nexus-cli
+++ b/jobdone-nexus-cli
@@ -56,14 +56,27 @@ log() {
     echo "$(date +%Y-%m-%dT%H:%M:%S) - $1" | tee -a $log_file
 }
 
+# log params
+log "user: $user"
+log "zerotier_id: $zerotier_id"
+log "trmm_mesh_agent: $trmm_mesh_agent"
+log "trmm_api_url: $trmm_api_url"
+log "trmm_client_id: $trmm_client_id"
+log "trmm_site_id: $trmm_site_id"
+log "trmm_auth_key: $trmm_auth_key"
+log "static_ip: $static_ip"
+log "gateway: $gateway"
+log "netmask: $netmask"
+log "dns: $dns"
+
 # install basic pacakges as root
-apt update &>> $log_file || { log "Failed to update apt."; exit 1; }
-apt install -y curl sudo unzip vim htop git net-tools wget ncdu network-manager &>> $log_file || { log "Failed to install basic packages."; exit 1; }
+apt update || { log "Failed to update apt."; exit 1; }
+apt install -y curl sudo unzip vim htop git net-tools wget ncdu network-manager || { log "Failed to install basic packages."; exit 1; }
 
 # k3s
 if ! k3s --version &> /dev/null; then
     log "Installing k3s without traefik..."
-    curl -sfL https://get.k3s.io | sudo K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="--disable traefik" sh - &>> $log_file || { log "Failed to install k3s."; exit 1; }
+    curl -sfL https://get.k3s.io | sudo K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="--disable traefik" sh - || { log "Failed to install k3s."; exit 1; }
     # directory creation
     [[ -d /home/$user/.kube ]] || mkdir /home/$user/.kube
     [[ -d ~/.kube ]] || mkdir ~/.kube
@@ -78,6 +91,7 @@ if ! k3s --version &> /dev/null; then
     sudo chown -R root ~/.kube/config
     # sleep
     sleep 10
+    log "k3s installed successfully."
 else
     log "k3s is already installed."
 fi
@@ -99,8 +113,9 @@ check_k3s_ready
 # argocd
 if ! kubectl get ns argocd &> /dev/null; then
     log "Installing ArgoCD..."
-    kubectl create namespace argocd &>> $log_file || { log "Failed to create ArgoCD namespace."; exit 1; }
-    kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml &>> $log_file || { log "Failed to install ArgoCD."; exit 1; }
+    kubectl create namespace argocd || { log "Failed to create ArgoCD namespace."; exit 1; }
+    kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml || { log "Failed to install ArgoCD."; exit 1; }
+    log "ArgoCD installed successfully."
 else
     log "ArgoCD is already installed."
 fi
@@ -109,10 +124,11 @@ fi
 if ! eget --version &> /dev/null; then
     log "Installing eget..."
     download_url=$(curl https://api.github.com/repos/zyedidia/eget/releases/latest -s | grep linux_amd64 | grep browser_download_url | cut -d '"' -f4)
-    curl -SsL ${download_url} -o /tmp/eget.tar.gz &>> $log_file || { log "Failed to download eget."; exit 1; }
-    tar -xf /tmp/eget.tar.gz --strip-components=1 -C /tmp/ &>> $log_file || { log "Failed to extract eget."; exit 1; }
-    sudo mv /tmp/eget /usr/local/bin/eget &>> $log_file || { log "Failed to move eget to /usr/local/bin."; exit 1; }
-    sudo chmod +x /usr/local/bin/eget &>> $log_file || { log "Failed to make eget executable."; exit 1; }
+    curl -SsL ${download_url} -o /tmp/eget.tar.gz || { log "Failed to download eget."; exit 1; }
+    tar -xf /tmp/eget.tar.gz --strip-components=1 -C /tmp/ || { log "Failed to extract eget."; exit 1; }
+    sudo mv /tmp/eget /usr/local/bin/eget || { log "Failed to move eget to /usr/local/bin."; exit 1; }
+    sudo chmod +x /usr/local/bin/eget || { log "Failed to make eget executable."; exit 1; }
+    log "eget installed successfully."
 else
     log "eget is already installed."
 fi
@@ -121,6 +137,7 @@ fi
 if ! k9s version &> /dev/null; then
     log "Installing k9s to /usr/local/bin"
     sudo /usr/local/bin/eget -q --to /usr/local/bin derailed/k9s --asset=tar.gz --asset=^sbom || { log "Failed to install k9s."; exit 1; }
+    log "k9s installed successfully."
 else
     log "k9s is already installed."
 fi
@@ -128,8 +145,9 @@ fi
 # zerotier
 if ! zerotier-cli info &> /dev/null; then
     log "Setting up ZeroTier..."
-    curl -s https://install.zerotier.com | sudo bash &>> $log_file || { log "Failed to install ZeroTier."; exit 1; }
-    sudo zerotier-cli join $zerotier_id &>> $log_file || { log "Failed to join ZeroTier network."; exit 1; }
+    curl -s https://install.zerotier.com | sudo bash || { log "Failed to install ZeroTier."; exit 1; }
+    sudo zerotier-cli join $zerotier_id || { log "Failed to join ZeroTier network."; exit 1; }
+    log "ZeroTier setup complete."
 else
     log "ZeroTier is already installed."
 fi
@@ -137,9 +155,10 @@ fi
 # tacticalrmm agent
 if [ ! -f /usr/local/bin/rmmagent ]; then
     log "Installing TacticalRMM agent..."
-    wget https://raw.githubusercontent.com/netvolt/LinuxRMM-Script/main/rmmagent-linux.sh &>> $log_file || { log "Failed to download TacticalRMM script."; exit 1; }
+    wget https://raw.githubusercontent.com/netvolt/LinuxRMM-Script/main/rmmagent-linux.sh || { log "Failed to download TacticalRMM script."; exit 1; }
     sudo chmod +x rmmagent-linux.sh
-    sudo ./rmmagent-linux.sh install 'amd64' $trmm_mesh_agent $trmm_api_url $trmm_client_id $trmm_site_id $trmm_auth_key server &>> $log_file || { log "Failed to install TacticalRMM agent."; exit 1; }
+    sudo ./rmmagent-linux.sh install 'amd64' $trmm_mesh_agent $trmm_api_url $trmm_client_id $trmm_site_id $trmm_auth_key server || { log "Failed to install TacticalRMM agent."; exit 1; }
+    log "TacticalRMM agent installed successfully, check if the token was accepted."
 else
     log "TacticalRMM agent is already installed."
 fi
