fix(cli): add zerotier-join to the cli

diff --git a/jobdone-nexus-cli b/jobdone-nexus-cli
--- a/jobdone-nexus-cli
+++ b/jobdone-nexus-cli
@@ -2,7 +2,7 @@
 
 # Check if the first argument is "install"
 if [ "$1" != "install" ]; then
-    echo "Usage: $0 install --hostname <hostname> --zerotier-ip-prefix <zerotier_ip_prefix> --trmm-mesh-agent <trmm_mesh_agent> --trmm-api-url <trmm_api_url> --trmm-client-id <trmm_client_id> --trmm-site-id <trmm_site_id> --trmm-auth-key <trmm_auth_key> --static-ip <static_ip> --gateway <gateway> --netmask <netmask> --dns <dns>"
+    echo "Usage: $0 install --hostname <hostname> --ssh-private-key-name <ssh_private_key_name> --ssh-public-key-name <ssh_public_key_name> --zerotier-network-id <zerotier_network_id> --zerotier-ip-prefix <zerotier_ip_prefix> --trmm-mesh-agent <trmm_mesh_agent> --trmm-api-url <trmm_api_url> --trmm-client-id <trmm_client_id> --trmm-site-id <trmm_site_id> --trmm-auth-key <trmm_auth_key> [--static-ip <static_ip>] [--gateway <gateway>] [--netmask <netmask>] [--dns <dns>]"
     exit 1
 fi
 shift # Remove the 'install' argument, leaving only the named parameters
@@ -23,6 +23,7 @@ EOF
 hostname=""
 ssh_private_key_name=""
 ssh_public_key_name=""
+zerotier_network_id=""
 zerotier_ip_prefix=""
 trmm_mesh_agent=""
 trmm_api_url=""
@@ -42,6 +43,7 @@ while [[ "$#" -gt 0 ]]; do
         --hostname) hostname="$2"; shift ;;
         --ssh-private-key-name) ssh_private_key_name="$2"; shift ;;
         --ssh-public-key-name) ssh_public_key_name="$2"; shift ;;
+        --zerotier-network-id) zerotier_network_id="$2"; shift ;;
         --zerotier-ip-prefix) zerotier_ip_prefix="$2"; shift ;;
         --trmm-mesh-agent) trmm_mesh_agent="$2"; shift ;;
         --trmm-api-url) trmm_api_url="$2"; shift ;;
@@ -74,7 +76,7 @@ if [ -z "$hostname" ] || \
     [ -z "$trmm_client_id" ] || \
     [ -z "$trmm_site_id" ] || \
     [ -z "$trmm_auth_key" ]; then
-    echo "Usage: $0 install --hostname <hostname> --zerotier-ip-prefix <zerotier_ip_prefix> --trmm-mesh-agent <trmm_mesh_agent> --trmm-api-url <trmm_api_url> --trmm-client-id <trmm_client_id> --trmm-site-id <trmm_site_id> --trmm-auth-key <trmm_auth_key> --static-ip <static_ip> --gateway <gateway> --netmask <netmask> --dns <dns>"
+    echo "Usage: $0 install --hostname <hostname> --ssh-private-key-name <ssh_private_key_name> --ssh-public-key-name <ssh_public_key_name> --zerotier-network-id <zerotier_network_id> --zerotier-ip-prefix <zerotier_ip_prefix> --trmm-mesh-agent <trmm_mesh_agent> --trmm-api-url <trmm_api_url> --trmm-client-id <trmm_client_id> --trmm-site-id <trmm_site_id> --trmm-auth-key <trmm_auth_key> [--static-ip <static_ip>] [--gateway <gateway>] [--netmask <netmask>] [--dns <dns>]"
     exit 1
 fi
 # Define log file with timestamp
@@ -118,13 +120,6 @@ else
     exit 1
 fi
 
-# Check if there is an interface that starts with "zt" (zerotier) and a zerotier ip with the ip prefix and set the zerotier_ip variable
-zerotier_ip=$(ip -4 addr show | grep "inet" | grep "zt" | grep "$zerotier_ip_prefix" | awk '{print $2}' | cut -d'/' -f1)
-if [ -z "$zerotier_ip" ]; then
-    log ERROR "No ZeroTier IP found with the prefix $zerotier_ip_prefix."
-    exit 1
-fi
-
 # set timezone to UTC
 log INFO "Setting timezone to UTC..."
 sudo timedatectl set-timezone UTC || { log ERROR "Failed to set timezone to UTC."; exit 1; }
@@ -152,6 +147,52 @@ sudo apt upgrade -y || { log ERROR "Failed to upgrade packages."; exit 1; }
 sudo apt install -y curl unzip vim htop git net-tools wget ncdu tmux || { log ERROR "Failed to install basic packages."; exit 1; }
 # sudo apt install -y iperf3 # note iperf requires an interactive prompt
 log INFO "Basic packages installed successfully."
+
+# install zerotier
+if ! zerotier-cli -v &> /dev/null; then
+    log INFO "Installing ZeroTier..."
+    curl -s https://install.zerotier.com | sudo bash || { log ERROR "Failed to install ZeroTier."; exit 1; }
+    log INFO "ZeroTier installed successfully."
+
+    # Join the ZeroTier network
+    log INFO "Joining ZeroTier network $networkID..."
+    sudo zerotier-cli join $networkID || { log ERROR "Failed to join ZeroTier network."; exit 1; }
+
+    # Wait for ZeroTier request to be approved
+    log INFO "Waiting for ZeroTier network $networkID request to be approved..."
+
+    timeout=600 # 10 minutes in seconds
+    start_time=$(date +%s)
+    while true; do
+        current_time=$(date +%s)
+        elapsed_time=$((current_time - start_time))
+        remaining_time=$((timeout - elapsed_time))
+
+        if [ $remaining_time -le 0 ]; then
+            log ERROR "Timeout reached. ZeroTier network $networkID request was not approved in time."
+            exit 1
+        fi
+
+        if sudo zerotier-cli listnetworks | grep "$networkID" | grep " OK " > /dev/null; then
+            log INFO "ZeroTier network $networkID request approved!"
+            break
+        else
+            time_min=$((remaining_time / 60))
+            time_sec=$((remaining_time % 60))
+            log INFO "Waiting for ZeroTier network $networkID request to be approved... ${time_min}m ${time_sec}s remaining"
+            sleep 5
+        fi
+    done
+else
+    log WARN "ZeroTier is already installed."
+fi
+
+# Check if there is an interface that starts with "zt" (zerotier) and a zerotier ip with the ip prefix and set the zerotier_ip variable
+zerotier_ip=$(ip -4 addr show | grep "inet" | grep "zt" | grep "$zerotier_ip_prefix" | awk '{print $2}' | cut -d'/' -f1)
+if [ -z "$zerotier_ip" ]; then
+    log ERROR "No ZeroTier IP found with the prefix $zerotier_ip_prefix."
+    exit 1
+fi
 
 # Ensure root's .ssh directory exists
 sudo mkdir -p /root/.ssh
